### ISSUE TITLE
TODO: Make JSON Merge function

### ISSUE THREAD

**Issue by dauten** [SIUE-Library/contentDM-Export#1]
Make a function that take multiple JSON/CSV files that have some fields and common and other fields distinct and returns one structure that has both.  For example take:
csvA=title,name,date=(id1,dale,11/14),(id2,jacob,8/1)
csvB=title,location,description=(id3,chicago,in winter)
then merge(csvA,csvB) should give something like
csvC=title,name,date,location,description=(id1,dale,11/14,null,null),(id2,jacob,8/1,null,null),(id3,null,null,chicago,in winter)

If that makes sense

**Comment by Jake-Grubb** [comment]
I fixed my birthday being wrong, asshole. =(

**Comment by dauten** [comment]
shhh

**Comment by dauten** [comment]
Looks like this can be done somehow using the python JSON library so we don't need a fancy algorithm for this or anything.
