### ISSUE TITLE
Find a way to scrape the ID's of every item in each collection

### ISSUE THREAD

**Issue by Jake-Grubb** [SIUE-Library/contentDM-Export#4]
We need a way to list the ID of every item in each collection. This could present a problem, because the ID's to not appear to be contiguous, or follow a specific pattern.

**Comment by dauten** [comment]
collection:id number should be our format which would give us something like
/sie_civilw:82
/sie_civilw:83
/sie_civilw:84
/sie_alum:120
/sie_alum:121
We can do this as an id->collection hashtable
or if we want to use objects for when we export to csv/json we can have an object like
csvItem():
  title=...
  collection=/sie_civilw
  id=82

etc...

**Comment by dauten** [comment]
These are included in the JSON dump
