### ISSUE TITLE
Map CONTENTdm Fields to DublinCore

### ISSUE THREAD

**Issue by dauten** [SIUE-Library/contentDM-Export#5]
Both apparently use dublincore extended but we may need to remap names

**Comment by dauten** [comment]
Should look like

Title->dcterms:title
Description->dcterms:description
Subjects->dcterms:subject
Rights->dcterms:rights
Language->dcterms:language

**Comment by Jake-Grubb** [comment]
Working in an excel spreadsheet to map over all unique ContentDM fields to DublinCore standards

**Comment by Jake-Grubb** [comment]
This isn't something I am really qualified to do, we should send this to Marlee

**Comment by dauten** [comment]
Marlee finished Friday
