### ISSUE TITLE
Verify reusability

### ISSUE THREAD

**Issue by dauten** [SIUE-Library/contentDM-Export#6]
Minimize hard coded values to allow it to be used by anyone with proper input values

**Comment by Jake-Grubb** [comment]
We can do this, although we will need to accept additional parameters, including:
1. ContentDM admin page
2. CARLI Site
3. ContentDM credentials
--and maybe--
 4. Omeka site

**Comment by Jake-Grubb** [comment]
Refactored README file to increase readability and reusability for others.

**Comment by dauten** [comment]
Right now there are a lot of harcoded values still so I'm going to implement a config.ini file.
